<?php

//TODO Ensure that the menu is rebuilt!

function civicrm_create_user_civicrm_config( &$config ) {
	
    $template =& CRM_Core_Smarty::singleton( );
    $root = dirname( __FILE__ );
    $template_root = $root . DIRECTORY_SEPARATOR . 'templates';
    
    if ( is_array( $template->template_dir ) ) {
        array_unshift( $template->template_dir, $template_root );
    } else {
        $template->template_dir = array( $template_root, $template->template_dir );
    }
    
    //Register php directory
   	$include_path = $template_root . PATH_SEPARATOR . get_include_path( );
    set_include_path( $include_path );
    $include_path = $root . PATH_SEPARATOR . get_include_path( );
    set_include_path( $include_path );
}

function civicrm_create_user_civicrm_xmlMenu( &$files ) {
	$files[]=dirname( __FILE__ ).DIRECTORY_SEPARATOR.'CreateUser.xml';
}

function civicrm_create_user_civicrm_summaryActions( &$actions, $contactID ){
	//need to implement this hook once 4.1 is out so that this appears automatically
}



